enum ActionTypes {
  ADD_ROUTE = 'ADD_ROUTE',
  DELETE_ROUTE = 'DELETE_ROUTE',
  RESET_CURRENT_ROUTE = 'RESET_CURRENT_ROUTE',
  SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE',
  UPDATE_NEW_ROUTE_TITLE = 'UPDATE_NEW_ROUTE_TITLE',
}

export default ActionTypes;
