enum ActionTypes {
  ADD_WAYPOINT = 'ADD_WAYPOINT',
  DELETE_WAYPOINT = 'DELETE_WAYPOINT',
  RESET_PLANNER = 'RESET_PLANNER',
  SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE',
  UPDATE_WAYPOINT = 'UPDATE_WAYPOINT',
}

export default ActionTypes;
